<?php
$helper = Mage::helper("cadence_fbpixel");
if (!$helper->isVisitorPixelEnabled()) {
    return;
}
$id = $helper->getVisitorPixelId();
?>
<!-- Facebook Tracking Pixel for Visitors -->
<script>(function() {
        var _fbq = window._fbq || (window._fbq = []);
        if (!_fbq.loaded) {
            var fbds = document.createElement('script');
            fbds.async = true;
            fbds.src = '//connect.facebook.net/en_US/fbds.js';
            var s = document.getElementsByTagName('script')[0];
            s.parentNode.insertBefore(fbds, s);
            _fbq.loaded = true;
        }
        _fbq.push(['addPixelId', '<?php echo $id ?>']);
    })();
    window._fbq = window._fbq || [];
    window._fbq.push(['track', 'PixelInitialized', {}]);
</script>
<noscript><img height="1" width="1" alt="" style="display:none" src="https://www.facebook.com/tr?id=<?php echo $id ?>&amp;ev=PixelInitialized" /></noscript>